### ISSUE TITLE
Enabling Monitor Shows Downtime

### ISSUE THREAD

**Issue by annezazuu** [Automattic/jetpack-beta#11]
I enabled monitor on my pressable staging site and it immediately showed me a message about downtime which was a bit concerning:

<img width="387" alt="screen shot 2016-07-20 at 9 56 24 pm" src="https://cloud.githubusercontent.com/assets/11266471/17011660/e984373c-4ec4-11e6-9870-d47ebe3c1210.png">

I think the "empty state" should definitely not show this.

**Comment by jeherve** [comment]
Moving this issue to https://github.com/Automattic/jetpack/issues/4474
