### ISSUE TITLE
Security threat UI Improvements

### ISSUE THREAD

**Issue by annezazuu** [Automattic/jetpack-beta#12]
This layout for showing security threats seems a bit off! Improving the styling might help folks see the threat better and respond. 

<img width="422" alt="screen shot 2016-07-20 at 3 08-1 46 pm" src="https://cloud.githubusercontent.com/assets/11266471/17030763/e6f63022-4f25-11e6-94d0-dc79050029da.png">

**Comment by jeherve** [comment]
I believe this should be fixed with the latest Alpha. Do you still get the threat notification? If so, could you update?
