### ISSUE TITLE
Rename Publicize settings

### ISSUE THREAD

**Issue by annezazuu** [Automattic/jetpack-beta#13]
Link to old settings sounds not so great. Can we change it to something like the following?

- Link to Settings
- Settings
- Configure Publicize
- Connect Accounts

There's no reason to say these are old settings!

<img width="746" alt="screen shot 2016-07-20 at 9 58-1 22 pm" src="https://cloud.githubusercontent.com/assets/11266471/17030812/249ffffc-4f26-11e6-935a-52379adea19c.png">

**Comment by jeherve** [comment]
Moved to https://github.com/Automattic/jetpack/issues/4498
