### ISSUE TITLE
Testing List: activate Markdown from the list

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack-beta#14]
Steps to reproduce:
1. Activate Jetpack and the Beta plugin.
2. Go to Jetpack > Settings, and disable the Markdown module.
3. Go to Jetpack > Beta
4. Instead of linking to the settings page to enable the Markdown module, we should offer a button to activate Markdown from there.

**Comment by lancewillett** [comment]
Even better would be just to parse the output into readable HTML/CSS with no need to enable or disable a Jetpack module. Do the work — don't make people think. :)

**Comment by jeherve** [comment]
Now fixed.
