### ISSUE TITLE
Plugin Details should offer meaningful information

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack-beta#15]
> If you try to “View Details” about a beta version, you get something like this:

![screen-shot-2016-05-30-at-12-22-41-pm](https://cloud.githubusercontent.com/assets/426388/19721896/8e032c90-9b74-11e6-9484-7fd238d937c3.png)

> Seems like that should be a list of what’s changing/needs testing, to help prime people on what to look for.

Reported here: p1HpG7-3fP-p2

**Comment by enejb** [comment]
I don't think this is relevant any more.
