### ISSUE TITLE
Jetpack plugin deleted when latest RC selected

### ISSUE THREAD

**Issue by ebinnion** [Automattic/jetpack-beta#2]
If I update after selecting the "Release candidates only" option on the Jetpack beta admin page at `/wp-admin/admin.php?page=jetpack-beta`, I notice that the Jetpack plugin is deleted after I refresh the page.

Demo video: https://cloudup.com/iNAbUKVm4BO

**Comment by enejb** [comment]
This is also really old plugin code. And this shouldn't happen. 

Now we do the following. We have a jetpack-dev folder that contains the experimental (RC, master) version of jetpack and a regular jetpack (stable) version that we run side by side and switch between the 2 versions. 
When we deactivate jetpack-beta we delete the jetpack-dev folder and switch back to running the stable jetpack version.
