### ISSUE TITLE
Remote Manifest Cache life is a bit too long if you are mid-development

### ISSUE THREAD

**Issue by roccotripaldi** [Automattic/jetpack-beta#26]
This is a minor gripe. Today when I was testing a branch that I was editing frequently, I noticed I had to wait a bit for the Beta plugin to recognize changes to my branch.

In doing some digging, I noticed that the remote manifest is cached for 15 minutes.

It would be nice to have a cache buster of some sort, or maybe shorten the cache life for the remote manifest.

**Comment by enejb** [comment]
That's a great idea!

**Comment by rclations** [comment]
👍 Just ran into this myself - would be a great feature add.
In the meantime, it would be great to have the cache info available somewhere more direct so testers know what to expect for the cache & refresh times.

**Comment by enejb** [comment]
This should be fixed. We always grab the latest version if the user is installing/updating or when viewing info on the settings page.
