### ISSUE TITLE
Fatal Error on install

### ISSUE THREAD

**Issue by jeherve** [Automattic/jetpack-beta#27]
> I installed the Jetpack Beta plugin in order to test this, and the entire /wp-admin/ section of my site became inaccessible due to a fatal error:

```
PHP Fatal error:  Cannot access empty property in wp-content/plugins/jetpack-beta-master/jetpack-beta.php on line 504
```

`Jetpack_Beta::get_branch_and_section_dev()` is returning `[ false, false ]`, which `Jetpack_Beta::get_new_jetpack_version()` doesn’t seem prepared to handle. It does this:

`if ( isset( $manifest->{$section}->{$branch}->version ) ) {`

`Jetpack_Beta::get_install_url()` appears to suffer from the same bug.

PHP 5.2.17

Reported in p8oabR-3s-p2

**Comment by designsimply** [comment]
Tested and confirmed using the following steps:

1. Download the Jetpack Beta Tester plugin from https://jetpack.com/download-jetpack-beta/
1. Go to WP Admin > Plugins > Add New.
1. Click the "Upload Plugin" button.
1. Upload the jetpack-beta-master.zip file.
1. Activate the Jetpack Beta Tester Plugin.

<strong>Result:</strong> wp-admin is no longer accessible and the following fatal error appears:

> Fatal error: Cannot access empty property in /home1/madefos6/public_html/wp/wp-content/plugins/jetpack-beta-master/jetpack-beta.php on line 504

![screen shot 2017-08-02 at wed aug 2 1 29 23 pm](https://user-images.githubusercontent.com/1119271/28891129-a501a8ec-7786-11e7-8349-213048cbac80.png)
<sup>Seen at http://madefortesting.com/wp/wp-admin/plugins.php?activate=true&plugin_status=all&paged=1&s= using Firefox 54.0.1 on Mac OS X 10.12.5.</sup>

Tested using madefortesting.com running WP 4.8, JP 5.2, and PHP 5.4.24 hosted at Bluehost.

**Comment by enejb** [comment]
I wasn't able to replicate this with the latest master. Feel free to open this if this is still the case.
