### ISSUE TITLE
Bleeding edge option not working

### ISSUE THREAD

**Issue by designsimply** [Automattic/jetpack-beta#29]
While testing Jetpack Beta 5.1, I found that none of the updates for 5.1 were present with the Jetpack > Jetpack Beta > Bleeding Edge option activated but the updates showed up as soon as I switched to Jetpack > Jetpack Beta > Release Candidate.

<strong>Video:</strong> [3m19s](https://cloudup.com/cbQn_kc6y6c)

![screen shot 2017-06-30 at fri jun 30 12 17 12 pm](https://user-images.githubusercontent.com/1119271/27748823-1e3e65dc-5d8e-11e7-90ab-80893853e033.png)
<sup>Seen at http://alittletestblog.com/wp-admin/admin.php?page=jetpack-beta using Safari 10.1.1 on Mac OS X 10.12.5.</sup>

Tested with

* WordPress 4.9-alpha-40964
* Jetpack 5.1-beta-12093-b247114-master and 5.1-beta-12182-36aa299-master
* Jetpack Beta Tester plugin 2.0.3
* PHP 5.6
* WP Engine
* Safari 10.1.1
* Mac OS X 10.12.5

**Comment by zinigor** [comment]
In conversation with @designsimply we have figured that this is not a bug, it was caused by a delay in the build. If you experience this again, please feel free to reopen.
