### ISSUE TITLE
PHP Notice / Warning

### ISSUE THREAD

**Issue by kraftbj** [Automattic/jetpack-beta#4]
I haven't seen this before:

`Notice: The plugin metadata file does not contain the required 'name' and/or 'version' keys. in /home/kraftbj/public_html/wp-content/plugins/jetpack-beta-master/plugin-updates/plugin-update-checker.php on line 922`

`Warning: Creating default object from empty value in /home/kraftbj/public_html/wp-content/plugins/jetpack-beta-master/plugin-updates/plugin-update-checker.php on line 227`

**Comment by enejb** [comment]
I am closing this since the code has changed some much and this error should not show up any more.
