### ISSUE TITLE
Cannot update to the latest Jetpack Beta or RC via Calypso

### ISSUE THREAD

**Issue by designsimply** [Automattic/jetpack-beta#48]
Steps to reproduce:

1. Start with a site with the Jetpack Beta Tester plugin active and set to use release candidates and wait for the release candidate to be updated.
1. In Calypso, go to My Sites and click the update icon next to the site. 

<strong>Result:</strong> it says "All plugins on {site name} are up to date" even though it's giving me an update notification icon next to the site and there is an RC update waiting for Jetpack.

<strong>Video:</strong> [48s](https://cloudup.com/cqL1LIoGaIU)

![conflicting-update-messages-for-jetpack-with-the-beta-tester-plugin](https://user-images.githubusercontent.com/1119271/35827138-20e8379e-0a78-11e8-938f-29cd58d403d1.png)
<sup>Tested with Opera 50.0.2762.58 on macOS 10.13.3 for http://wpcomsupport9.com/ running WordPress 4.9.2 and Jetpack 5.8-beta-17449-9e6b904-branch-5.8 hosted at SiteGround.</sup>

**Comment by kraftbj** [comment]
This was duplicated by https://github.com/Automattic/jetpack/issues/18422 but I moved that one over to the JP repo first. Closing this one.
