### ISSUE TITLE
Jetpack Beta should not install a broken build.

### ISSUE THREAD

**Issue by oskosk** [Automattic/jetpack-beta#51]
Yesterday, a build created by the beta builder, was broken. A lot of files like `jetpack.php` were missing.

The sites where I have Jetpack Beta with Bleeding Edge running and autoupdates enabled, got this build installed anyways, but given that `jetpack.php` was not present, the plugin was not recognized by WordPress, so my Jetpack installations was absent. Calypso reported problems, but not monitor, as it's still able to ping the site's xmlrpc.

We should probably do some basic checks before letting a build be installed. Otherwse, autoudpates are completely broken from that point on for users of this plugin.

**Comment by enejb** [comment]
This got Fixed! No more broken builds!
