### ISSUE TITLE
Feature: Add error logging

### ISSUE THREAD

**Issue by sirreal** [Automattic/jetpack-beta#67]
It would be helpful to report errors so that a dashboard and alerts could be setup to spot errors early. This is especially relevant for bleeding edge (master), which is essentially continuous deployment.

**Comment by enejb** [comment]
What kind of error logging do you have in mind? Can you elaborate a bit more?

We already have tests that are supposed to catch error in master. 

There are plugins out there that help display PHP errors in the wp-admin. See https://wordpress.org/plugins/wp-log-viewer/

You just need to configure your environment.

**Comment by sirreal** [comment]
> What kind of error logging do you have in mind? Can you elaborate a bit more?

It would be very nice to know about fatals being caused.

> We already have tests that are supposed to catch error in master.

They don't catch everything 🙂 

> There are plugins out there that help display PHP errors in the wp-admin.

I'm not concerned with seeing errors for my site, I know how to do that. I'm interested in seeing errors "in the wild" that could help us proactively fix problems before users need to reach out to us.

A recent case this would've helped with: p1549647737424600-slack-jetpack-gutenberg

**Comment by enejb** [comment]
I think this is a great idea. ❤️ and I have some ideas how we can implement it.

**Comment by jeherve** [comment]
This was done in #91
