### ISSUE TITLE
Beta plugin fails to install beta Jetpack - "Updated Failed"

### ISSUE THREAD

**Issue by lschuyler** [Automattic/jetpack-beta#9]
Site is using Jetpack 4.0.3. I installed the Jetpack Beta Tester plugin and activated it. It then shows there is an update available for Jetpack:

![screen shot on 2016-06-18 at 11-02-51](https://cloud.githubusercontent.com/assets/4307088/16172799/c0167cf0-3544-11e6-9cbf-c519e5d4598d.png)

I click the 'Update Now' link but the update fails:

![screen shot 2016-06-18 at 11 03 10 am](https://cloud.githubusercontent.com/assets/4307088/16172796/aec93406-3544-11e6-919c-56d0cd7da91e.png)

Tried on two sites and a multi-site with the same result on each.

**Comment by lschuyler** [comment]
I was able to get a successful beta update after toggling the bleeding edge/stable option in the Beta settings.

**Comment by enejb** [comment]
I think this is related to the older version of the Jetpack beta tester plugin. 
Closing this for now.
